// my-sveltekit-app/src/lib/CreativeEditorSDK.svelte
<script>
    import CreativeEditorSDK from '@cesdk/cesdk-js';
    import { onDestroy, onMount } from 'svelte';
  
    // reference to the container HTML element where CE.SDK will be initialized
    let container = null;
    // where to keep track of the CE.SDK instance
    let cesdk = null;
  
    // deafult CreativeEditor SDK configuration
    const defaultConfig = {
      license: '<YOUR_LICENSE_KEY>', // replace it with a valid CE.SDK license key
      callbacks: { onUpload: 'local' }, // enable local file uploads in the Asset Library
      // other default configs...
    };
  
    // accessing the component's props
    const { el, children, class: _, config, ...props } = $props();
  
    // hook to initialize the CreativeEditorSDK component
    onMount(() => {
      // integrate the configs read from props with the default ones
      const ceSDKConfig = {
        ...defaultConfig,
        ...config,
      };
  
      try {
        // initialize the CreativeEditorSDK instance in the container element
        // using the given config
        if (container) {
          CreativeEditorSDK.create(container, ceSDKConfig).then(async instance => {
            cesdk = instance;
  
            // do something with the instance of CreativeEditor SDK (e.g., populate
            // the asset library with default / demo asset sources)
            await Promise.all([
              cesdk.addDefaultAssetSources(),
              cesdk.addDemoAssetSources({ sceneMode: 'Design' }),
            ]);
  
            // create a new design scene in the editor
            await cesdk.createDesignScene();
          });
        }
      } catch (err) {
        console.warn(`CreativeEditor SDK failed to mount.`, { err });
      }
    });
  
    // hook to clean up when the component unmounts
    onDestroy(() => {
      try {
        // dispose of the CE.SDK instance if it exists
        if (cesdk) {
          cesdk.dispose();
          cesdk = null;
        }
      } catch (err) {
        // log error if CreativeEditor SDK fails to unmount
        console.warn(`CreativeEditor SDK failed to unmount.`, { err });
      }
    });
  </script>
  
  <!-- the container HTML element where the CE.SDK editor will be mounted -->
  <div id="cesdk_container" bind:this="{container}"></div>
  
  <style>
    /* styling for the CE.SDK container element to take full viewport size */
    #cesdk_container {
      height: 100vh;
      width: 100vw;
    }
  </style>

// my-react-app/src/CreativeEditorSDK.jsx
import CreativeEditorSDK from '@cesdk/cesdk-js';

import { useEffect, useRef } from 'react';

// configure CreativeEditor SDK
const config = {
  license: 'YOUR_LICENSE_KEY', // replace it with a valid CE.SDK license key
  callbacks: { onUpload: 'local' }, // enable local file uploads in the Asset Library
};

export default function CreativeEditorSDKComponent() {
  // reference to the container HTML element where CESDK will be initialized
  const cesdk_container = useRef(null);
  // define a state variable to keep track of the CESDK instance
  //const [cesdk, setCesdk] = useState(null);

  useEffect(() => {
    // prevent initialization if the container element is not available yet
    if (!cesdk_container.current) {
      return;
    }

    // flag to keep track of the component unmount
    let cleanedUp = false;
    // where to store the local CE.SDK instance
    let instance;

    // initialize the CreativeEditorSDK instance in the container HTML element
    // using the given config
    CreativeEditorSDK.create(cesdk_container.current, config).then(
      async _instance => {
        // assign the current CD.SDK instance to the local variable
        instance = _instance;

        if (cleanedUp) {
          instance.dispose();
          return;
        }

        // do something with the instance of CreativeEditor SDK (e.g.,  populate
        // the asset library with default / demo asset sources)
        await Promise.all([
          instance.addDefaultAssetSources(),
          instance.addDemoAssetSources({ sceneMode: 'Design' }),
        ]);

        // create a new design scene in the editor
        await instance.createDesignScene();

        // store the CESDK instance in state
        //setCesdk(instance);
      },
    );

    // cleanup function to dispose of the CESDK instance when the component unmounts
    const cleanup = () => {
      // clear the local state and dispose of the CS.SDK instance (if it has been assigned)
      cleanedUp = true;
      instance?.dispose();
      //setCesdk(null);
    };

    // to ensure cleanup runs when the component unmounts
    return cleanup;
  }, [cesdk_container]);

  return (
    // the container HTML element where the CESDK editor will be mounted
    <div
      ref={cesdk_container}
      style={{ width: '100vw', height: '100vw' }}
    ></div>
  );
}
